language: node_js

node_js:
  - node

branches:
  only:
    - master # will only build for master branch commits

before_script:
  - npm install -g --silent firebase-tools # installs firebase to run firebase deploy
  - npm install -g --silent @angular/cli
  - ng analytics off

script:
  - ng build --prod


