language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
    - master

script:
  - ng lint
  - ng build --prod --base-href https://florian8496.github.io/Adopte-un-dev/index.html
