language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run Adopte-un-dev -- --watch=false --browsers=ChromeHeadlessNoSandbox
